# Generated by Django 2.2.10 on 2020-02-12 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170311_1524'),
        ('accounts', '0006_auto_20190710_0058'),
    ]

    operations = [
    ]
